model:
  name: 'osnet_ain_x1_0'
  pretrained: False
  feature_dim: 512

data:
  type: 'image'
  sources: ['aic20']
  targets: ['aic20']
  height: 192
  width: 256
  combineall: False
  transforms:
    random_flip:
      enable: True
      p: 0.5
    random_erase:
      enable: True
      p: 0.5
  save_dir: 'log/osnet_ain_x1_0_aic20_softmax_cosinelr'

aic20:
  use_simulation_data: False

sampler:
  train_sampler: 'RandomSampler'
  num_instances: 4

loss:
  name: 'softmax'
  softmax:
    label_smooth: True
    conf_penalty: 0.0

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 64
  batch_size: 64
  fixbase_epoch: 2
  open_layers: ['classifier', 'fc']
  lr_scheduler: 'multi_step_warmup'
  stepsize: [20, 40]
  warmup: 3
  warmup_factor_base: 0.01

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  visactmap: False