model:
  name: 'osnet_ain_x1_0'
  pretrained: False
  feature_dim: 512

data:
  type: 'image'
  sources: ['aic20', 'vric', 'veri']
  targets: ['aic20', 'vric', 'veri']
  height: 192
  width: 256
  combineall: False
  transforms:
    color_jitter:
      enable: False
      p: 0.8
      saturation: 0.1
      hue: 0.1
      brightness: 0.15
      contrast: 0.15
    random_flip:
      enable: True
      p: 0.5
    random_erase:
      enable: True
      p: 0.5
      sl: 0.2
      sh: 0.4
      rl: 0.3
      rh: 1.7
    random_padding:
      enable: True
      p: 0.25
    random_crop:
      enable: True
      p: 0.25
      scale: 1.2
    random_rotate:
      enable: True
      p: 0.33
    random_perspective:
      enable: True
      p: 0.33
      distortion_scale: 0.3
    random_grid:
      enable: True
      p: 0.15
    random_figures:
      enable: True
      p: 0.33
  save_dir: 'log/osnet_ain_x1_0_aic20_softmax_cosinelr'

aic20:
  use_simulation_data: False
  simulation_data_only: False

sampler:
  train_sampler: 'RandomIdentitySamplerV3'
  num_instances: 4

loss:
  name: 'am_softmax'
  softmax:
    label_smooth: True
    conf_penalty: 0.0
    m: 0.35
    s: 15.0

metric_losses:
  enable: True
  center_coeff: 1.0
  glob_push_plus_loss_coeff: 1.2
  balance_losses: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 100
  batch_size: 64
  fixbase_epoch: 2
  open_layers: ['classifier', 'fc']
  lr_scheduler: 'multi_step_warmup'
  stepsize: [20, 60]
  warmup: 3
  warmup_factor_base: 0.01

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False
  visactmap: False
