model:
  name: 'osnet_ain_x1_0'
  pretrained: True
  download_weights: False
  feature_dim: 256
  bn_eval: False
  bn_frozen: False

data:
  type: 'image'
  sources: [['veri'], ['compcars']]
  targets: ['veri', 'cityflow']
  height: 192
  width: 256
  combineall: False
  transforms:
    color_jitter:
      enable: False
      p: 0.8
      saturation: 0.1
      hue: 0.1
      brightness: 0.15
      contrast: 0.15
    random_flip:
      enable: True
      p: 0.5
    random_erase:
      enable: True
      p: 0.5
      sl: 0.2
      sh: 0.4
      rl: 0.3
      rh: 3.3
    random_padding:
      enable: True
      p: 0.25
    random_crop:
      enable: False
      p: 0.25
      scale: 1.2
    random_rotate:
      enable: True
      p: 0.33
    random_perspective:
      enable: False
      p: 0.33
      distortion_scale: 0.3
    random_grid:
      enable: True
      p: 0.15
    random_figures:
      enable: True
      p: 0.33
    mixup:
      enable: False
      p: 0.33
      alpha: 0.2
  save_dir: 'log/osnet_ain_x1_0_general'

sampler:
  train_sampler: 'RandomIdentitySamplerV3'
  num_instances: 4

loss:
  name: 'am_softmax'
  softmax:
    conf_penalty: 0.085
    label_smooth: True
    pr_product: False
    m: 0.35
    s: 15.0
    end_s: -1.0
    duration_s: -1
    skip_steps_s: -1

metric_losses:
  enable: True
  center_coeff: 1.0
  triplet_coeff: 1.0

reg:
  ow: False
  ow_beta: 1e-2

train:
  optim: 'sgd'
  lr: 0.01
  max_epoch: 90
  batch_size: 112
  fixbase_epoch: 5
  open_layers: ['conv5', 'classifier', 'fc']
  lr_scheduler: 'multi_step_warmup'
  stepsize: [40, 70]
  warmup: 5
  warmup_factor_base: 0.005
  frozen_factor_base: 1.0

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False
  visactmap: False
