model:
  name: 'osnet_ain_x1_0'
  pretrained: False
  feature_dim: 512

data:
  type: 'image'
  sources: ['aic20']
  targets: ['aic20']
  height: 192
  width: 256
  combineall: False
  transforms: ['random_flip', 'random_erase']
  save_dir: 'log/osnet_ain_x1_0_aic20_softmax_cosinelr'

aic20:
  use_simulation_data: False

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

loss:
  name: 'softmax'
  softmax:
    label_smooth: True
    conf_penalty: 0.085

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 250
  batch_size: 64
  fixbase_epoch: 5
  open_layers: ['classifier', 'fc']
  lr_scheduler: 'cosine'

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  visactmap: False