model:
  name: 'osnet_ain_x1_0'
  pretrained: True
  download_weights: False
  feature_dim: 256
  bn_eval: False
  bn_frozen: False
  enable_attentions: False

data:
  type: 'image'
  sources: [['veri', ], ['universemodels']]
  targets: ['veri', 'cityflow']
  height: 208
  width: 208
  combineall: False
  enable_masks: True
  transforms:
    color_jitter:
      enable: False
      p: 0.1
      saturation: 0.1
      hue: 0.1
      brightness: 0.15
      contrast: 0.15
    random_gray_scale:
      enable: False
      p: 0.1
    random_flip:
      enable: True
      p: 0.5
    random_erase:
      enable: True
      p: 0.5
      sl: 0.2
      sh: 0.4
      rl: 0.3
      rh: 3.3
    random_padding:
      enable: True
      p: 0.25
    random_crop:
      enable: True
      p: 0.25
      scale: 0.92
    random_rotate:
      enable: True
      p: 0.33
    random_grid:
      enable: True
      p: 0.15
    random_figures:
      enable: True
      p: 0.33
    random_background_substitution:
      enable: True
      p: 0.25
  save_dir: 'log/osnet_ain_x1_0_general'

sampler:
  train_sampler: 'RandomIdentitySamplerV3'
  batch_num_instances: 4
  epoch_num_instances: 28

loss:
  name: 'am_softmax'
  softmax:
    conf_penalty: 0.085
    label_smooth: True
    pr_product: True
    m: 0.35
    s: 15.0
    end_s: -1.0
    duration_s: -1
    skip_steps_s: -1
  projector_weight: -1.0

metric_losses:
  enable: True
  center_coeff: 1.0
  triplet_coeff: 1.0

reg:
  ow: False
  ow_beta: 1e-2

train:
  optim: 'sgd'
  lr: 0.01
  max_epoch: 70
  batch_size: 112
  fixbase_epoch: 5
  open_layers: ['conv5', 'fc', 'classifier']
  lr_scheduler: 'multi_step_warmup'
  stepsize: [30, 50]
  warmup: 5
  warmup_factor_base: 0.005
  frozen_factor_base: 1.0

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False
  visactmap: False
